project:
  type: book
  resources:
    - dataset/**

book:
  title: "Introduction to Probability"
  author: 
    - name: "Zeming WANG"
      affiliations: "Southwest University of Finance and Economics"
  date: "26 January 2025"
  chapters:
    - index.qmd
    - part: "Probability Basics" 
      chapters:
        - chapters/01_intro.qmd
        - chapters/02_event.qmd
        - chapters/03_classic.qmd
        - chapters/04_gambling.qmd
        - chapters/05_birthday.qmd
        - chapters/06_axioms.qmd
        - chapters/07_cond.qmd
        - chapters/08_montyhall.qmd
        - chapters/09_simpson.qmd
        - chapters/10_indep.qmd
        - chapters/11_dating.qmd
        - chapters/11_calculus.qmd
        - chapters/01_baseR.qmd
    - part: "Random Variables"
      chapters:
        - chapters/12_rv.qmd
        - chapters/13_data.qmd
        - chapters/14_disc.qmd
        - chapters/15_cont.qmd
        - chapters/16_cdf.qmd
    - part: "Discrete Distributions"
      chapters:
        - chapters/18_bin.qmd
        - chapters/20_dexp.qmd
        - chapters/21_hgeom.qmd
        - chapters/22_geom.qmd
        - chapters/22_hhht.qmd
        - chapters/22_nbin.qmd
        - chapters/23_joint.qmd
        - chapters/23_condist.qmd
        - chapters/24_pois.qmd
        - chapters/26_birthday2.qmd
        - chapters/27_convolution.qmd
        - chapters/19_dice.qmd
        - chapters/27_ratings.qmd
    - part: "Expectation and Variance"
      chapters:
        - chapters/28_exp.qmd
        - chapters/29_lifexp.qmd
        - chapters/30_twoenvp.qmd
        - chapters/31_linearity.qmd
        - chapters/32_median.qmd
        - chapters/33_var.qmd
        - chapters/34_cov.qmd
        - chapters/34_portfolio.qmd
        - chapters/35_condexp.qmd
        - chapters/36_mgf.qmd
        - chapters/37_ineq.qmd
    - part: "Continuous Distributions"
      chapters:
        - chapters/40_contd.qmd
        - chapters/41_unif.qmd
        - chapters/42_gauss.qmd
        - chapters/42_sumrvs.qmd
        - chapters/42_normal.qmd
        - chapters/42_mvn.qmd
        - chapters/43_expo.qmd
        - chapters/44_gamma.qmd
        - chapters/45_beta.qmd
        - chapters/47_trans.qmd
        - chapters/46_2rvs.qmd
    - part: "Sampling distributions"
      chapters:
        - chapters/50_lln.qmd
        - chapters/51_clt.qmd
        - chapters/52_samples.qmd
        - chapters/53_estimator.qmd
        - chapters/54_ci.qmd
        - chapters/55_ht.qmd

format:
  html:
    theme: cosmo
    page-layout: article
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
  pdf:
    documentclass: scrreprt

editor: source
